bitcoind:
  build: .
  dockerfile: Dockerfile
  #image: christroutner/bitcoind-bch:0.19.07
  container_name: bitcoind
  ports:
    - "8332:8332"   # RPC mainnet port
    - "8333:8333"   # p2p mainnet port
    - "28332:28332" # ZMQ port
  volumes:
    - ../blockchain-data/bch-mainnet-abc:/data
  restart: always
